import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Team.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {/* <div className="unset-img ">
        <Image
          alt="Mountains"
          src="/hero-image.png"
          layout="fill"
          className="custom-img"
        />
      </div> */}

      <header>
        <div className="col-span-full z-0">
          {/* <Image
            src="/hero-image.png"
            layout="fill"
            objectFit="contain"
            objectPosition="top"
            className=""
          /> */}
          {/* <img src="/hero-image.png" className=" -mt-24" /> */}
        </div>

        <div
          class="bg-local "
          // style={{background-image: url(/hero-image.png)}}
        />
      </header>

      {/* <div className=" z-10  text-lg text-black px-36">tes</div> */}

      <main>
        <div class="grid grid-rows-5 grid-cols-12 grid-flow-col gap-4 pt-36 ">
          <div class="col-span-4 col-start-3 row-start-2">
            <span className=" font-bold text-5xl">Your hub for teamwork </span>
          </div>
          <div class=" col-span-4 col-start-3 row-start-3">
            <span>
              Project discussions, important documents, free food announcements:
              they all live tidily together in Team. With your team and
              information in one easily searchable place, collaborating online
              is as easy as collaborating in person.
            </span>
          </div>
          <div class=" col-span-2 col-start-3 row-start-4">
            <span>Learn More</span>
          </div>
          <div class="row-span-full row-start-1 col-end-13 col-start-7 ">
            <Image src="/Meeting-1.png" width={716} height={672} />
          </div>
        </div>

        <div class="grid grid-rows-5 grid-cols-12 grid-flow-col gap-4 p-36">
          <div class="row-span-full row-start-1 col-start-2 col-end-7  ">
            <Image src="/simpletask-image.png" width={1030} height={644} />
          </div>
          <div class="col-span-4 col-start-8 row-start-2">
            <span className=" font-bold text-5xl">Your hub for teamwork </span>
          </div>
          <div class=" col-span-4 col-start-8 row-start-3">
            <span>
              Project discussions, important documents, free food announcements:
              they all live tidily together in Team. With your team and
              information in one easily searchable place, collaborating online
              is as easy as collaborating in person.
            </span>
          </div>
          <div class=" col-span-2 col-start-8 row-start-4">
            <span>Learn More</span>
          </div>
        </div>

        <div class="grid grid-rows-5 grid-cols-12 grid-flow-col gap-4 pb-36 ">
          <div class="col-span-4 col-start-3 row-start-2">
            <span className=" font-bold text-5xl">Your hub for teamwork </span>
          </div>
          <div class=" col-span-4 col-start-3 row-start-3">
            <span>
              Project discussions, important documents, free food announcements:
              they all live tidily import Footer from './../components/Footer';
              together in Team. With your team and information in one easily
              searchable place, collaborating online is as easy as collaborating
              in person.
            </span>
          </div>
          <div class=" col-span-2 col-start-3 row-start-4">
            <span>Learn More</span>
          </div>
          <div class="row-span-full row-start-1 col-end-12 col-start-7 ">
            <Image src="/scheduling-image.png" width={472} height={544} />
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
